### ISSUE TITLE
[프로그래머스] 이중우선순위큐 질문

### ISSUE THREAD

**Issue by thals0** [lake041/sesac-algorithm#1]
문제 링크 : [이중우선순위큐](https://school.programmers.co.kr/learn/courses/30/lessons/42628)

``` python
from heapq import *
def solution(operations):
    q = []
    for i in operations:
        op, n = i.split()
        if op == 'I':
            heappush(q, int(n))
        elif op == 'D' and len(q) != 0:
            if n == "-1":
                heappop(q)
            else:
                q.sort()
                q.pop()
    if q:
        return [max(q), q[0]]
    else:
        return [0,0]
```

"D 1" 즉, 최댓값을 삭제하는 경우 
최댓값이 리프 노드에 있다는 것은 보장되지만 가장 끝 노드(인덱스)에 있다는 것은 보장되지 않기 때문에 q.sort() 해줬습니다
이때 트리구조가 무너져서 실패할 거라고 생각했는데 통과함
heappush나 heappop를 하면서 트리구조를 되찾는건지 ? 아니면 테케가 부족해서 운좋게 통과한 건지 ? 모르겠어서 질문 남김니당 >>

**Comment by thals0** [comment]
https://www.acmicpc.net/problem/7662 
백준에 같은 문제가 있어서 넣어봤는데 시간초과 발생
![image](https://github.com/lake041/sesac-algorithm/assets/101865071/f377cc35-0ee1-4247-817c-7c53fd769fa2)

**Comment by oxboxx** [comment]
https://docs.python.org/ko/3/library/heapq.html

"heap.sort()는 힙의 불변성(invariant)을 유지합니다!"

공식 문서 보니까 sort 해도 힙이 유지된대요! 신기하네용 ㅋㅋ
시간 초과는 매번 sort() 하는 게 비효율적이라 그런 것 같습니다.
프로그래머스 테스트 케이스가 좀 부실한 것 같아요.

**Comment by knowmetoowell** [comment]
q.sort()는 시간복잡도가 높아서 sort를 사용할 거면 굳이 힙자료구조를 사용할 필요가 없다고 생각합니다.
그래서 백준에 같은 문제가 시간 초과된 것 같아요

**Comment by thals0** [comment]
헉 그러네요 감사합니다 !!

**Comment by knowmetoowell** [comment]
heappush나 heappop를 하면서 트리구조를 되찾는건지 ?
-> heapq가 어차피 최소힙으로 되어 있어서 sort해도 첫값은 똑같아서 통과한 것 같아요!

**Comment by thals0** [comment]
앗 근데 민재님 답변해주신거 보면 sort()해도 불변성은 유지해준다는거 아닌가요 ?!

**Comment by knowmetoowell** [comment]
![image](https://github.com/lake041/sesac-algorithm/assets/87797445/9a351be3-4a67-41f7-bcdf-2b6814b48fd1)
요기서 invariant 하다는 게 정확히 어떤건지 모르겠어요 ㅠㅠ
찾아봐도 정확히 설명되어 있는 느낌은 없고 저는 '최소힙에서 최솟값이 heap[0] 위치에 오게 유지한다' 정도로 이해했습니다
그래서 다음과 같이 테스트 하면
```python
lst2 =[9,8,7,6,5]
heapq.heappush(lst2, 1)
print(lst2)
print(sorted(lst2))
```
이렇게 테스트하면 결국
![image](https://github.com/lake041/sesac-algorithm/assets/87797445/c63811d4-68d4-491a-ba07-37a2535e25e0)
요렇게 나와서 순서의 불변을 유지한다기 보다는 단지 최솟값이 heap[0] 위치에 오게 유지 정도로 이해하는게 맞는 것 같아요!

**Comment by thals0** [comment]
근데 불변이 맞을수도 있는게 아래처럼 print말고 heappop으로 하면 sort여부와 관계없이 똑같이 나오네용 

``` python 
lst1 = [9,8,7,6,5]
heapify(lst1)
heappush(lst1, 1)
print(lst1)
for _ in range(len(lst1)):
  print(heappop(lst1))
print("                  ")
lst2 =[9,8,7,6,5]
heapify(lst2)
heappush(lst2, 1)
print(lst2)
lst2.sort()
print(lst2)
for _ in range(len(lst2)):
  print(heappop(lst2))
```

```
1
5
6
7
8
9

1
5
6
7
8
9
```

**Comment by thals0** [comment]
엇 근데 문득 든 생각인데 lst2는 heap이 아닌 상태 인건가요 .. ?
![image](https://github.com/lake041/sesac-algorithm/assets/101865071/8364e2e9-974c-48c9-94c1-df4250332b79)

``` python
lst2 =[9,8,7,6,5]
heappush(lst2, 1)
for _ in range(len(lst2)):
  print(heappop(lst2))
```
하나씩 heappop했는데 결과가 아래처럼 나오네요 .. ?!
```
1
8
5
6
7
9
```

**Comment by oxboxx** [comment]
1. 최상위 노드는 항상 최솟값이다.
2. 부모 노드는 자식 노드보다 작거나 같다. (부모 인덱스가 k이면 자식 노드 인덱스는 2k+1, 2k+2)

힙의 불변성은 이 두 가지를 의미하는 것 같고 이 두가지 조건을 만족한다면 힙인 것 같습니다.
sort()를 수행하면 트리 구조가 깨지는 것처럼 보이지만

1. list[0]가 최솟값이고
2. list[k]가 list[2k+1], list[2k+2]보다 작거나 같음은 자명하기 때문에 (왼쪽 원소가 오른쪽 원소보다 작거나 같음)

sort()를 수행해도 여전히 힙이라고 보면 될 것 같습니다.

**Comment by oxboxx** [comment]
> ![image](https://user-images.githubusercontent.com/87797445/281626311-9a351be3-4a67-41f7-bcdf-2b6814b48fd1.png) 요기서 invariant 하다는 게 정확히 어떤건지 모르겠어요 ㅠㅠ 찾아봐도 정확히 설명되어 있는 느낌은 없고 저는 '최소힙에서 최솟값이 heap[0] 위치에 오게 유지한다' 정도로 이해했습니다 그래서 다음과 같이 테스트 하면
> 
> ```python
> lst2 =[9,8,7,6,5]
> heapq.heappush(lst2, 1)
> print(lst2)
> print(sorted(lst2))
> ```
> 
> 이렇게 테스트하면 결국 ![image](https://user-images.githubusercontent.com/87797445/281626462-c63811d4-68d4-491a-ba07-37a2535e25e0.png) 요렇게 나와서 순서의 불변을 유지한다기 보다는 단지 최솟값이 heap[0] 위치에 오게 유지 정도로 이해하는게 맞는 것 같아요!

invariant는 순서까지 같다는 말은 아니고 여전히 힙이다~ 라는 의미 같아요

**Comment by knowmetoowell** [comment]
> 엇 근데 문득 든 생각인데 lst2는 heap이 아닌 상태 인건가요 .. ? ![image](https://user-images.githubusercontent.com/101865071/281638168-8364e2e9-974c-48c9-94c1-df4250332b79.png)
> 
> ```python
> lst2 =[9,8,7,6,5]
> heappush(lst2, 1)
> for _ in range(len(lst2)):
>   print(heappop(lst2))
> ```
> 
> 하나씩 heappop했는데 결과가 아래처럼 나오네요 .. ?!
> 
> ```
> 1
> 8
> 5
> 6
> 7
> 9
> ```

오,, 그렇네용ㅠ 죄송합니당ㅠㅠ


> 1. 최상위 노드는 항상 최솟값이다.
> 2. 부모 노드는 자식 노드보다 작거나 같다. (부모 인덱스가 k이면 자식 노드 인덱스는 2k+1, 2k+2)
> 
> 힙의 불변성은 이 두 가지를 의미하는 것 같고 이 두가지 조건을 만족한다면 힙인 것 같습니다. sort()를 수행하면 트리 구조가 깨지는 것처럼 보이지만
> 
> 1. list[0]가 최솟값이고
> 2. list[k]가 list[2k+1], list[2k+2]보다 작거나 같음은 자명하기 때문에 (왼쪽 원소가 오른쪽 원소보다 작거나 같음)
> 
> sort()를 수행해도 여전히 힙이라고 보면 될 것 같습니다.

이 설명 들으니 확실히 이해가 됐습니당ㅎㅎ 감사합니다!

**Comment by thals0** [comment]
와오 감사합니다 여러분 .. >> 이해 완입니다
