### ISSUE TITLE
특정 기간동안 대여 가능한 자동차들의 대여비용 구하기 sql 질문 

### ISSUE THREAD

**Issue by thals0** [lake041/sesac-algorithm#2]
[특정 기간동안 대여 가능한 자동차들의 대여비용 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/157339)

``` sql
select c.car_id, car_type, c.daily_fee
        from CAR_RENTAL_COMPANY_CAR c join CAR_RENTAL_COMPANY_RENTAL_HISTORY r
        on c.CAR_ID = r.CAR_ID
        where CAR_TYPE in ('SUV', '세단') and c.car_id not in (date_format(end_date, '%Y-%m-%d') > '2022-11-01')
```

date_format(end_date, '%Y-%m-%d') > '2022-11-01') 여기서 '2023-10-1'을 왜 못 걸러내는 지 몰겠써여 

``` sql
select car_id, car_type, daily_fee
        from CAR_RENTAL_COMPANY_CAR
        where CAR_TYPE in ('SUV', '세단') and 
      car_id not in (select CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY where date_format(end_date, '%Y-%m-%d') > '2022-11-01')
```
이 코드는 걸러 냄

**Comment by knowmetoowell** [comment]
c.car_id not in (date_format(end_date, '%Y-%m-%d') > '2022-11-01')

요렇게 쓰면 car_id 가 (yyyy-MM-dd) 등에 포함되지 않는 것을 출력하니까
안 걸러져용
만약 car_id 가 5고 end_date 가 2023-11-01 이면
저 조건은 where 5 != '2023-11-01' 인 조건이니 당연히 True가 되서 그냥 없는 조건이나 다름없어용

**Comment by thals0** [comment]
참고로 mysql 입니당

**Comment by knowmetoowell** [comment]
c.car_id not in (date_format(end_date, '%Y-%m-%d') > '2022-11-01')

요렇게 쓰면 car_id 가 (date_format(end_date, '%Y-%m-%d') > '2022-11-01') 등에 포함되지 않는 것을 출력하니까
안 걸러져용
괄호안에 조건문이 들어가서 1이나 0 이 출력되요
만약 car_id 가 5고 end_date 가 2023-11-02 이면
저 조건은 where 5 != 1 인 조건이니 당연히 True가 되서 그냥 없는 조건이나 다름없어용

select c.car_id, car_type, c.daily_fee,(date_format(end_date, '%Y-%m-%d') > '2022-11-01')
        from CAR_RENTAL_COMPANY_CAR c join CAR_RENTAL_COMPANY_RENTAL_HISTORY r
        on c.CAR_ID = r.CAR_ID
        where CAR_TYPE in ('SUV', '세단') and c.car_id not in (date_format(end_date, '%Y-%m-%d') > '2022-11-01')

이 쿼리 실행해보면 저 조건에 만족하면 1 만족안하면 0을 출력하는 것을 알 수 있어요

**Comment by oxboxx** [comment]
```sql
c.car_id not in (select CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY where date_format(end_date, '%Y-%m-%d') > '2022-11-01')
```
오타 나신 듯
이렇게 하면 걸러질 겁니다

근데 2022-11-01 < end_date인지 2022-11-01 <= end_date인지 모르겠어요
데이터 중에 2022-11-01 00시 00분에 끝나는 게 하나 있거든요
뇌피셜로는 2022-11-01 땡 치자 마자 바로 쓸 수 있는 거니까 등호 빼는 게 맞는 거 같긴 해요
근데 정답 코드에서는 어차피 다른 조건 때문에 걸러져서 등호 붙이나 안 붙이나 결과는 똑같아요

```sql
select c.car_id, car_type, c.daily_fee
from CAR_RENTAL_COMPANY_CAR c join CAR_RENTAL_COMPANY_RENTAL_HISTORY r
on c.CAR_ID = r.CAR_ID
```
그리고 이렇게 조인하고 where절로 조건 거르시면 car_id가 중복이 행들이 많이 생기는데 한 번 출력해보시면 감 잡으실 거 같아요
